// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseFooter: typeof import('./src/components/layouts/BaseFooter.vue')['default']
    BaseHeader: typeof import('./src/components/layouts/BaseHeader.vue')['default']
    BaseLogo: typeof import('./src/components/base/BaseLogo.vue')['default']
    BaseModal: typeof import('./src/components/base/BaseModal.vue')['default']
    BasePage: typeof import('./src/components/layouts/BasePage.vue')['default']
    BaseRow: typeof import('./src/components/base/BaseRow.vue')['default']
    BaseTable: typeof import('./src/components/base/BaseTable.vue')['default']
    ConfirmDialog: typeof import('./src/components/ui/ConfirmDialog.vue')['default']
    ConfirmModal: typeof import('./src/components/ui/ConfirmModal.vue')['default']
    CrudActions: typeof import('./src/components/ui/CrudActions.vue')['default']
    DashboardLayout: typeof import('./src/components/layouts/DashboardLayout.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputCkEditor: typeof import('./src/components/form/InputCkEditor.vue')['default']
    InputRadio: typeof import('./src/components/form/InputRadio.vue')['default']
    InputSelect: typeof import('./src/components/form/InputSelect.vue')['default']
    InputSimpleText: typeof import('./src/components/form/InputSimpleText.vue')['default']
    InputText: typeof import('./src/components/form/InputText.vue')['default']
    InputTextArea: typeof import('./src/components/form/InputTextArea.vue')['default']
    PageRow: typeof import('./src/components/base/PageRow.vue')['default']
    Pagination: typeof import('./src/components/ui/Pagination.vue')['default']
    PaginationLinks: typeof import('./src/components/ui/PaginationLinks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SimplePagination: typeof import('./src/components/ui/SimplePagination.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
